import {HDP, RF} from '@helpers';
import {family, palette} from '@theme';
import {Dimensions, Platform, StyleSheet} from 'react-native';

const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    display: 'flex',
    backgroundColor: palette.white,
    position: 'relative',
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: HDP(Platform.OS === 'android' ? 10 : 70),
    paddingBottom: HDP(0),
    marginHorizontal: (0.1 * width) / 2,
  },
  mailText: {
    color: '#00000080',
    fontSize: RF(10),
    fontFamily: family.Regular,
    textAlign: 'left',
  },
  topView: {
    borderBottomLeftRadius: HDP(16),
    borderBottomRightRadius: HDP(16),
    paddingBottom: HDP(4),
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    zIndex: 2,
    elevation: 4,
  },
  userDet: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  welcomeText: {
    color: palette.white,
    fontSize: RF(14),
    fontFamily: family.Bold,
    textTransform: 'capitalize',
  },
  addText: {
    color: palette.white,
    fontSize: RF(14),
    fontFamily: family.Bold,
  },
  nameText: {
    color: palette.white,
    fontSize: RF(12),
    fontFamily: family.Regular,
    textTransform: 'capitalize',
  },
  numText: {
    color: palette.white,
    fontSize: RF(14),
    fontFamily: family.Medium,
  },
  cardContent: {
    paddingTop: HDP(7),
    paddingBottom: HDP(12),
    borderRadius: HDP(16),
    width: width,
    marginRight: 100,
    paddingLeft: (0.1 * width) / 2,
  },
  acctCount: {
    color: palette.green,
    fontSize: RF(10),
    alignSelf: 'center',
    fontFamily: family.Bold,
  },
  acctCountSpan: {
    color: palette.green,
    fontSize: RF(10),
    fontFamily: family.Medium,
    alignSelf: 'center',
  },
  acctGrid: {
    justifyContent: 'space-between',
    marginBottom: HDP(20),
    marginTop: HDP(12),
    backgroundColor: 'rgba(43, 61, 56, 0.3)',
    marginRight: HDP(20),
    paddingHorizontal: HDP(20),
    width: width * 0.7,
    borderRadius: HDP(5),
    paddingVertical: HDP(10),
  },
  acctDropGrid: {
    alignSelf: 'center',
    backgroundColor: 'rgba(173, 216, 230, 0.8)',
    width: width * 0.9,
    paddingVertical: HDP(10),
    paddingHorizontal: HDP(20),
    borderRadius: HDP(5),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  acctAmt: {
    color: palette.white,
    fontSize: RF(8),
    fontFamily: family.Bold,
  },
  acctDropAmt: {
    color: palette.dark,
    fontSize: RF(8),
    fontFamily: family.Bold,
  },
  acctNo: {
    color: palette.green,
    fontSize: RF(10),
    fontFamily: family.Bold,
  },
  acctDropNo: {
    color: palette.asphalt,
    fontSize: RF(10),
    fontFamily: family.Bold,
  },
  acctName: {
    color: palette.white,
    fontSize: RF(12),
    fontFamily: family.Regular,
  },
  acctBorder: {
    borderRightWidth: 1,
    paddingHorizontal: 20,
    borderRightColor: palette.white,
    maxWidth: 0.5 * width,
  },
  upgradeCard: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,

    elevation: 4,
    backgroundColor: palette.white,

    borderBottomRightRadius: HDP(16),
    borderBottomLeftRadius: HDP(16),
    paddingHorizontal: HDP(32),
    marginTop: HDP(-25),
  },
  upgradeCardContent: {
    display: 'flex',
    flexDirection: 'row',
    paddingRight: HDP(10),
  },
  upgradeLabel: {
    fontSize: RF(12),
    fontFamily: family.Medium,
    color: '#007bcf',
  },
  upgradeText: {
    fontSize: RF(12),
    fontFamily: family.Regular,
    color: palette.asphalt,
    maxWidth: width * 0.9,
    flex: 1,
  },
  upgradeCta: {
    color: palette.peace,
    fontSize: RF(14),
    fontFamily: family.Medium,
  },
  paymentCta: {
    display: 'flex',
    flexDirection: 'row',
    paddingHorizontal: HDP(32),
  },
  payCtaText: {
    fontSize: RF(12),
    fontFamily: family.Medium,
  },
  payBtnRec: {
    borderRadius: HDP(12),
    paddingHorizontal: HDP(0),
  },
  payBtnSend: {
    borderRadius: HDP(12),
    paddingHorizontal: HDP(0),
    backgroundColor: palette.blue,
  },
  otherCtaSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: HDP(32),
  },
  otherCtaHeader: {
    color: palette.purple,
    fontSize: RF(14),
    fontFamily: family.Bold,
  },
  otherCtaItem: {
    backgroundColor: palette.white,
    paddingTop: HDP(16),
    paddingBottom: HDP(8),
    borderRadius: HDP(8),
    width: 0.1 * height,
    borderColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  otherCtaItemText: {
    textAlign: 'center',
    color: palette.blue,
    fontSize: RF(10),
  },
  transEmptyView: {
    paddingHorizontal: HDP(16.25),
  },
  transHeader: {
    color: palette.purple,
    fontSize: RF(14),
    fontFamily: family.Medium,
  },
  transSub: {
    fontFamily: family.Regular,
    fontSize: RF(12),
    color: palette.someText,
    paddingBottom: HDP(10),
  },
  transData: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: palette.white,
    paddingVertical: HDP(10),
    paddingHorizontal: HDP(12),
    marginBottom: HDP(20),
    borderRadius: HDP(2),
    shadowColor: '#03cf00',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  transContainer: {
    marginBottom: HDP(24),
    paddingHorizontal: HDP(20),
  },
  transDate: {
    fontSize: RF(10),
    fontFamily: family.Medium,
    color: palette.concord,
  },
  transName: {
    fontSize: RF(12),
    fontFamily: family.Regular,
    color: palette.purple,
    textTransform: 'capitalize',
  },
  transMode: {
    fontSize: RF(12),
    fontFamily: family.Regular,
    color: palette.masala,
    marginTop: HDP(5),
  },
  transAmt: {
    fontSize: RF(10),
    fontFamily: family.SemiBold,
    color: palette.purple,
    textTransform: 'uppercase',
  },
  transStatus: {
    fontSize: RF(8),
    fontFamily: family.Medium,
    textTransform: 'uppercase',
  },
  payOverLay: {
    position: 'absolute',
    backgroundColor: '#FFFFFFC9',
    height: '100%',
    width: '100%',
    top: 20,
    zIndex: 20,
    display: 'flex',
  },
  receiveTxt: {
    fontSize: RF(10),
    fontFamily: family.Regular,
    color: palette.purple,
    alignSelf: 'center',
    textAlign: 'center',
  },
  payItem: {
    backgroundColor: palette.white,
    paddingTop: HDP(11),
    paddingBottom: HDP(6),
    paddingHorizontal: HDP(10),
    borderRadius: HDP(16),
    width: HDP(85),
    marginRight: HDP(11),
    borderColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  amtText: {
    fontFamily: family.Bold,
    fontSize: RF(24),
    color: palette.white,
  },
  amtDropText: {
    fontFamily: family.Bold,
    fontSize: RF(12),
    color: '#03cf00',
  },
  acctText: {
    fontFamily: family.Regular,
    fontSize: RF(12),
    color: '#03cf00',
  },
  acctDropText: {
    fontFamily: family.Bold,
    fontSize: RF(12),
    color: palette.black,
  },
  curr: {
    fontWeight: '900',
    fontSize: RF(12),
    color: palette.white,
    alignSelf: 'center',
  },
  currDrop: {
    fontWeight: '900',
    fontSize: RF(10),
    color: '#03cf00',
  },
  acctDets: {
    display: 'flex',
    flexDirection: 'row',
  },
  numTitle: {
    fontFamily: family.Regular,
    fontSize: RF(12),
    color: '#EFFFCC',
  },
  numNo: {
    fontFamily: family.Medium,
    fontSize: RF(12),
    color: '#fff',
  },
  createNew: {
    backgroundColor: 'rgba(128, 187, 1, 0.2)',
    paddingHorizontal: 7,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  createNewText: {
    fontSize: 10,
    fontFamily: family.Medium,
    color: 'white',
  },
  upgradeTextWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    width: width,
    justifyContent: 'space-between',
  },
  disableBox: {
    backgroundColor: '#00000050',
  },

  modalBox: {
    backgroundColor: '#fff',
    width: width,
    alignSelf: 'center',
    borderRadius: HDP(32),
    paddingVertical: HDP(48),
    paddingHorizontal: HDP(32),
  },
  txHeader: {
    color: palette.purple,
    fontSize: RF(16),
    fontFamily: family.Medium,
  },
  txStatusBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#DBDBDB',
    paddingBottom: HDP(24),
    alignItems: 'flex-start',
  },
  txAmt: {
    fontSize: RF(20),
    fontFamily: family.Regular,
    color: '#263238',
  },
  txType: {
    color: palette.purple,
    fontSize: RF(14),
    fontFamily: family.Regular,
    textTransform: 'capitalize',
    marginTop: HDP(8),
  },
  txStat: {
    fontFamily: family.Regular,
    textTransform: 'capitalize',
    fontSize: RF(10),
  },
  txList: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#DBDBDB',
    paddingVertical: HDP(22),
  },
  txListLabel: {
    color: '#455A64',
    fontFamily: family.Regular,
    fontSize: RF(9),
  },
  txListText: {
    color: '#455A64',
    fontFamily: family.Regular,
    fontSize: RF(9),
    textTransform: 'capitalize',
  },
  txDotBox: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  txClose: {
    position: 'absolute',
    right: HDP(26),
    top: HDP(26),
  },
  modalNotif: {
    fontSize: RF(14),
    fontFamily: family.Regular,
    color: palette.purple,
    alignSelf: 'center',
    textAlign: 'center',
    width: '80%',
  },
  modalBtn: {
    width: '80%',
    alignSelf: 'center',
  },

  main: {
    padding: HDP(10),
    borderRadius: HDP(20),
    backgroundColor: '#fff',
  },
  alert: {
    fontSize: RF(18),
    fontFamily: family.Medium,
    color: '#6CCF00',
    textAlign: 'center',
    marginTop: 32,
  },
  message: {
    fontSize: 14,
    fontFamily: family.Medium,
    color: '#A5A5A5',
    textAlign: 'center',
    marginBottom: 30,
  },
  snap2: {
    width: 250,
    height: 250,
    alignSelf: 'center',
  },
  numDe: {
    color: '#A5A5A5',
    fontSize: RF(12),
    marginTop: HDP(8),
    textAlign: 'center',
  },
  numSpan: {
    color: '#6CCF00',
    fontSize: RF(12),
    marginTop: HDP(8),
    fontFamily: family.Medium,
  },
  firstMode: {
    transform: [{rotate: '90deg'}],
  },
  showMode: {
    transform: [{rotate: '-90deg'}],
  },
  allCta: {
    color: '#6CCF00',
    fontSize: RF(14),
    marginTop: HDP(8),
    fontFamily: family.Medium,
    alignSelf: 'center',
  },
  transCTA: {
    paddingHorizontal: HDP(20),
  },
  trueBox: {
    backgroundColor: '#5DBE3F',
    width: HDP(15),
    height: HDP(15),
    borderRadius: HDP(8),
    marginRight: HDP(5),
  },
  failBox: {
    backgroundColor: 'red',
    width: HDP(15),
    height: HDP(15),
    borderRadius: HDP(8),
    marginRight: HDP(5),
  },
  pendBox: {
    backgroundColor: '#FFDE00',
    width: HDP(15),
    height: HDP(15),
    borderRadius: HDP(8),
    marginRight: HDP(5),
  },
  statBox: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stattext: {
    fontSize: RF(7),
    fontFamily: family.SemiBold,
    color: palette.black,
    textTransform: 'uppercase',
  },
  flexShare: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  boxBase: {
    borderWidth: 1,
    borderColor: palette.black,
    borderRadius: HDP(16),
    height: HDP(55),
    width: HDP(55),
    color: 'black',
    fontSize: RF(20),
  },
  boxHighLighted: {
    borderWidth: 1,
    borderColor: palette.black,
    borderRadius: HDP(16),
    height: HDP(55),
    width: HDP(55),
  },
  errtext: {
    fontSize: RF(7),
    fontFamily: family.Regular,
    color: 'red',
    textAlign: 'center',
    marginBottom: HDP(10),
  },
  transEmptyText: {
    fontSize: RF(10),
    fontFamily: family.Regular,
    color: palette.purple,
    textAlign: 'left',
    marginBottom: HDP(10),
  },
  showtext: {
    fontSize: RF(10),
    fontFamily: family.Regular,
    color: palette.purple,
    textAlign: 'center',
    // marginBottom: HDP(10),
  },
  addBox: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 'auto',
    marginBottom: 'auto',
  },
});

export default styles;
